// Generated by scripts/render-posters.mjs; do not edit by hand, rerun the script.
// The lockup each hero still baked behind its cards (nameRect()'s geometry),
// in CSS px of the cut's viewport from its top left.
import type { BakedLockup, StillCut } from "./heroStill";

export const HERO_STILL_RECTS: Readonly<Record<StillCut, BakedLockup>> = {
  wide: {
    left: 224.96,
    baseline: 563.88,
    width: 990.08,
    fontPx: 357.91,
    greeting: {
      left: 232.12,
      baseline: 308.53,
      fontPx: 64.42
    },
    gradient: {
      top: 321.12,
      height: 261.33
    }
  },
  square: {
    left: 156.22,
    baseline: 579.08,
    width: 687.55,
    fontPx: 248.55,
    greeting: {
      left: 161.19,
      baseline: 401.76,
      fontPx: 44.74
    },
    gradient: {
      top: 410.92,
      height: 180.65
    }
  },
  narrow: {
    left: 22.63,
    baseline: 461.65,
    width: 344.74,
    fontPx: 124.63,
    greeting: {
      left: 25.12,
      baseline: 372.74,
      fontPx: 22.43
    },
    gradient: {
      top: 377.35,
      height: 90.55
    }
  }
};
