"use client";

import ContributionSkyline from "./ContributionSkyline";
import { NumbersRow } from "./NumbersRow";
import { useContributions } from "./context";
import { isRolling, windowPeriod, yearOf } from "./derive";
import type { ContributionData } from "./data";
import { accentRamp, DAY_MS, dayMs, toKey } from "./skyline/maths";
import type { Settings } from "./settings";

// The skyline with whichever companions the panel picked, plus the strip
// variant (flat only). `replay` remounts it so the entrance plays again.

export function SampleTag() {
  return (
    <p className="m-label-sm mb-4 text-muted">
      <span className="m-placeholder">Sample year: generated by the component, not my data. Comparison only.</span>
    </p>
  );
}

type BlockProps = { settings: Settings; pin: number | null; replay: number };

// The calendar range the chart shows, shared with the ribbon. A rolling
// window (six or twelve months) is drawn the way GitHub draws its year: whole
// weeks from the Sunday on or before its first day, ending today, so it has no
// future to show (the six-month fixture already starts on that Sunday). The
// calendar year starts on January 1 (its first week padded) and may run on
// to December 31 as empty slabs.
const sundayOf = (date: string) => {
  const ms = dayMs(date);
  return toKey(ms - new Date(ms).getUTCDay() * DAY_MS);
};

export const chartRange = (d: ContributionData, s: Settings) =>
  isRolling(d)
    ? { from: sundayOf(d.range.from), through: undefined }
    : { from: d.range.from, through: s.future === "slabs" ? yearOf(d) + "-12-31" : undefined };

const common = (d: ContributionData, s: Settings, pin: number | null) => ({
  data: s.data === "real" ? d.days : undefined,
  endDate: d.fetched,
  range: chartRange(d, s),
  periodLabel: windowPeriod(d),
  totalLabel: d.window === "6mo" ? "Last 6 months" : d.window === "12mo" ? "Last 12 months" : yearOf(d) + " so far",
  palette: accentRamp(s.share),
  heightScale: s.heightScale,
  heightCurve: s.curve,
  levelCurve: s.levels,
  heightCap: s.heightCap,
  duration: s.duration,
  card: s.card,
  pin,
});

export function MetricsBlock({ settings: s, pin, replay }: BlockProps) {
  const d = useContributions();
  const key = [replay, s.view, s.data, s.future, d.window].join("-");
  return (
    <div>
      {s.data === "sample" && <SampleTag />}
      {s.companions === "numbers" && (
        <div className="mb-14 md:mb-20">
          <NumbersRow lead={s.lead} />
        </div>
      )}
      <ContributionSkyline
        key={key}
        {...common(d, s, pin)}
        defaultView={s.view}
        showStats={s.companions === "stats"}
        showTitle={s.companions !== "numbers"}
      />
    </div>
  );
}

export function MetricsStrip({ settings: s, pin, replay }: BlockProps) {
  const d = useContributions();
  return (
    <div>
      {s.data === "sample" && <SampleTag />}
      <ContributionSkyline
        key={[replay, s.data, s.future, d.window].join("-")}
        {...common(d, s, pin)}
        view="2d"
        orbit={false}
        showToggle={false}
        showStats={false}
        footer={null}
      />
    </div>
  );
}
